fixtures:
  repositories:
    "stdlib":
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "f496005bf3db8a5202bf9c16daf9a524b178c67a"
  symlinks:
    "pureftpd": "#{source_dir}"
